### ISSUE TITLE
Cannot find LineShapeExtract.m

### ISSUE THREAD

**Issue by mpschallmo** [romainVala/matspec#3]
Hi Romain,

I'm an Assistant Professor at the University of Minnesota working with Gosia Marjanska. She recommended your Matlab software package for pre-processing 7T STEAM data for analysis in LCModel.

My issue is that when running the example "doit.m" code, Matlab is unable to find LineShapeExtract.m, despite having the matspec folder in my path (i.e., addpath(genpath('foo/matspec')) )

Here's the function I'm trying to run (line 103 in doit.m):
> fwater = get_water_width(fwater);

And here's the error message:
> Undefined function 'LineShapeExtract' for input arguments of type 'double'.
> Error in get_water_width (line 27) [mConAmpCor mSPhase mT2used] = LineShapeExtract(ywat,sw);

Thanks for your help. Feel free to reach out to me directly for more information.

Best,
Michael-Paul Schallmo

**Comment by romainVala** [comment]
Hi
 I add the missing function. Just make a git pull.
Note this is still experimental since I give 3 different value for the water_width ...

Romain

**Comment by mpschallmo** [comment]
Hi Romain,

Excellent, this is now working for me.

Thank you!
Michael-Paul
