### ISSUE TITLE
Cannot find function 'complet_struct.m'

### ISSUE THREAD

**Issue by mpschallmo** [romainVala/matspec#4]
Hi Romain,

I am having an issue running processing_LCModel.m

When I get to line 8:
`par = complet_struct(par,defpar);`

I get the following error message:
>Undefined function 'complet_struct' for input arguments of type 'struct'.
> Error in processing_LCmodel (line 8)
> par = complet_struct(par,defpar);

I believe this is a missing function. Please advise.

Thank you,
Michael-Paul

**Comment by romainVala** [comment]
Hi, 
thanks for the report
Actually it comes from the related toolbox matvol, but ok  I just add it
Best

**Comment by mpschallmo** [comment]
Thank you! After the update, the code now runs to completion and generates the expected files.
